### ISSUE TITLE
modify kubeconfig file's user token to client-certificate-data and client-key-data

### ISSUE THREAD

**Issue by jzhao04** [kyma-project/terraform-module#72]
**Description**

The current kubeconfig file uses user token, but the token will expire very shortly, in CI/CD pipeline, we will first use your terraform code to create the kyma instance, after the kubeconfig file is generated, we will use this kubeconfig file  to deploy other k8s services in CI/CD pipelines, but the kubeconfig file will expire shortly, which blocks the deployment of other k8s services.

**Reasons**

Could you replace kubeconfig user's token to  client-certificate-data and client-key-data?

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: xxxx
    server: https://api.c-4087655.stage.kyma.ondemand.com
  name: garden-kyma-stage--c-4087655-external
contexts:
- context:
    cluster: garden-kyma-stage--c-4087655-external
    user: garden-kyma-stage--c-4087655-external
  name: garden-kyma-stage--c-4087655-external
- context:
    cluster: garden-kyma-stage--c-4087655-external
    user: garden-kyma-stage--c-4087655-external
  name: garden-kyma-stage--c-4087655-external
current-context: garden-kyma-stage--c-4087655-external
kind: Config
preferences: {}
users:
- name: garden-kyma-stage--c-4087655-external
  user:
    client-certificate-data: xxx
    client-key-data: xxx
```

thanks

Jane
